eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8100

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        #  include: health,beans,info,caches,conditions,configprops,env,flyway,heapdump,httptrace,integrationgraph,liquibase,logfile,loggers,mappings,metrics
        include: '*'
