eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
ribbon:
    ReadTimeout: 10000
server:
    port: 8762
spring:
    application:
        name: zuul-server
zuul:
    host:
        connect-timeout-millis: 20000
        socket-timeout-millis: 30000
    ignored-services: '*'
    routes:
        gallery-service:
            path: /gallery/**
            service-id: gallery-service
        image-service:
            path: /image-service/**
            service-id: image-service
