eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
                timeout:
                    enabled: false
server:
    port: 8100
spring:
    application:
        name: gallery-service
