eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
                timeout:
                    enabled: false
server:
    port: 8100
spring:
    application:
        name: gallery-service
management:
    endpoints:
        web:
            base-path: /manage
            exposure:
              #  include: health,beans,info,caches,conditions,configprops,env,flyway,heapdump,httptrace,integrationgraph,liquibase,logfile,loggers,mappings,metrics
                 include: '*'
